# Generated by Django 3.2.15 on 2022-09-12 19:36

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail_editable_help.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_editable_help_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sidebar',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.PageChooserBlock(help_text=wagtail_editable_help.models.HelpText('Home page', 'sidebar link', default='Choose up to 5 links')))], default='', use_json_field=None),
            preserve_default=False,
        ),
    ]
