# Generated by Django 3.2.15 on 2022-08-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpTextString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, editable=False, max_length=255, unique=True)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('identifier',),
            },
        ),
    ]
